### PR TITLE
LRAC-5601 Updates message in the SyncedSites when the AC connected to the portal is out of service

### PR DESCRIPTION
**Pull request by JhonattasFerreira**
https://issues.liferay.com/browse/LRAC-5601

### CODE REVIEW

**Comment by JhonattasFerreira** [comment]
ci:forward

**Comment by fcodias** [comment]
ci:forward

**Comment by fcodias** [comment]
ci:forward

**Comment by fcodias** [comment]
ci:test:sf

**Comment by JhonattasFerreira** [comment]
ci:forward

**Comment by yichenroy** [comment]
ci:forward

**Comment by JhonattasFerreira** [comment]
ci:stop

**Comment by fcodias** [comment]
ci:stop

**Pull request closed without merging**
